# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
  - name: myString
    displayName: string
    type: string
    default: mondodddd
    values:
    - mondoddddfff
    - mondodddd
  - name: myString22
    displayName: string22
    type: string
    default: 'world22'
    values:
    - world22
    - mondo22
  - name: destroy
    displayName: Destroy Environment?
    type: boolean
    default: false
  - name: pool
    type: string
    default: test

variables:
- name: TF_VAR_test_var
  value: ${{ parameters.myString }}

pool:
  name: Default

steps:
- script: echo Hello $(TF_VAR_test_var), ${{ parameters.myString }}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@0
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Trial(1)(851f27db-441a-4eab-9a57-1b622fbe2d4f)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform'
    backendAzureRmResourceGroupLocation: 'West Europe'
    backendAzureRmStorageAccountName: 'levin'
    backendAzureRmContainerName: 'states'
    backendAzureRmKey: 'test-env'
    allowTelemetryCollection: false
- ${{ if eq(parameters.destroy, false) }}:
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        environmentServiceName: 'Trial(851f27db-441a-4eab-9a57-1b622fbe2d4f)'
        runAzLogin: true
        commandOptions: '-out=$(System.DefaultWorkingDirectory)/terraform.tfplan -detailed-exitcode -var test_var=${{ parameters.myString }}'
        allowTelemetryCollection: true
        publishPlanResults: 'testingplan'
- ${{ if eq(parameters.destroy, false) }}:
    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        environmentServiceName: 'Trial(1)(851f27db-441a-4eab-9a57-1b622fbe2d4f)'
        runAzLogin: true
        commandOptions: '-var test_var=${{ parameters.myString }}'
        allowTelemetryCollection: false
- ${{ if eq(parameters.destroy, true) }}:
    - task: TerraformCLI@0
      inputs:
        command: 'destroy'
        environmentServiceName: 'Trial(1)(851f27db-441a-4eab-9a57-1b622fbe2d4f)'
        runAzLogin: true
        allowTelemetryCollection: false
        commandOptions: '-var test_var=${{ parameters.myString }}'