# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
  - name: myString
    displayName: string
    type: string
    default: 'worldааааеее'
    values:
    - worldааааеее
    - mondo
  - name: myString22
    displayName: string22
    type: string
    default: 'world22'
    values:
    - world22
    - mondo22
variables:
- name: TF_VAR_test_var
  value: ${{ parameters.myString }}

pool:
  name: Default

steps:
- script: echo Hello $(TF_VAR_test_var), ${{ parameters.myString }}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@0
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Trial(1)(851f27db-441a-4eab-9a57-1b622fbe2d4f)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform'
    backendAzureRmResourceGroupLocation: 'West Europe'
    backendAzureRmStorageAccountName: 'levin'
    backendAzureRmContainerName: 'states'
    backendAzureRmKey: 'test-env'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Trial(851f27db-441a-4eab-9a57-1b622fbe2d4f)'
    runAzLogin: true
    commandOptions: '-out=$(System.DefaultWorkingDirectory)/terraform.tfplan -detailed-exitcode -var test_var=$(TF_VAR_test_var)'
    allowTelemetryCollection: true
    publishPlanResults: 'testingplan'
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'Trial(1)(851f27db-441a-4eab-9a57-1b622fbe2d4f)'
    runAzLogin: true
    commandOptions: '-var test_var=$(TF_VAR_test_var)'
    allowTelemetryCollection: false
